#!/usr/bin/env bash
# Writes /opt/jobpilot/.env from environment variables (set by GitHub Actions).
set -euo pipefail

ENV_FILE=/opt/jobpilot/.env

cat > "$ENV_FILE" <<EOF
FRONTEND_URL=${FRONTEND_URL}
DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
QWEN_BASE_URL=${QWEN_BASE_URL}
QWEN_MODEL=${QWEN_MODEL}
PROFILE_LLM_MODEL=${PROFILE_LLM_MODEL}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
GITHUB_CLIENT_ID=${GH_OAUTH_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GH_OAUTH_CLIENT_SECRET}
GITHUB_REDIRECT_URI=${GH_OAUTH_REDIRECT_URI}
EOF

chmod 600 "$ENV_FILE"
